### PR TITLE
Fix vet issues

### LINKED ISSUE #38: Fix vet issues
There are a bunch of small issues that vet and lint will pick up on related to printing and formatting. It would be good to have those fixed.

_extra credit_: add a go tool vet pass to .travis.yml so we don't have to reopen this issue once the current formatting errors are fixed.

_note to implementors_: I'm not interested in PR's renaming variables to whatever vet thinks is a standard, that is beyond my tolerance for bike shedding.

### PR DESCRIPTION
**Pull request by joshi4**
add go vet to CI

Fixes #38

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -185,7 +185,7 @@ func visit(url *url.URL) {
 		fmt.Println(grayscale(14)(k+":"), color.CyanString(strings.Join(resp.Header[k], ",")))
 	}
 
-	fmt.Println("\nBody discarded\n")
+	fmt.Printf("\nBody discarded\n\n")
```
Comment (davecheney) [inline main.go]: wut?

Comment (joshi4) [inline main.go]: had to add this to match the current output.
